version: '3'
services:
  frontend:
    image: 
    ports:
  backend:
    image: 
    ports:
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
# Add frontend and backend
