version: '3'
services:
  frontend:
    # image: euclidesc/aemoja-frontend
    build: ./client
    ports: 
      - "3000:3000"
  backend:
    # image: euclidesc/aemoja-backend
    build: ./server
    env_file: ./server/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
# volumes:
#   db-data:
#     driver: flocker
#     driver_opts:
#       size: "10GiB"

